# Generated by Django 4.2.4 on 2023-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRentCar', '0010_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Sedan', 'Sedan'), ('Kombi', 'Kombi'), ('Suv', 'Suv'), ('Coupe', 'Coupe'), ('Shooting brake', 'Shooting brake'), ('Hatchback', 'Hatchback')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('Przedni', 'Przedni'), ('Tylni', 'Tylni'), ('4x4', '4x4')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Hybryda', 'Hybryda'), ('Benzyna', 'Benzyna'), ('Elektryczny', 'Elektryczny')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('7', '7'), ('6', '6'), ('8', '8'), ('5', '5')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuala', 'Manualna'), ('Automatyczna', 'Automatyczna')], max_length=32),
        ),
    ]
