# Generated by Django 4.2.4 on 2023-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRentCar', '0011_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalterms',
            old_name='premium_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='rentalterms',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rentals_count',
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Kombi', 'Kombi'), ('Suv', 'Suv'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Shooting brake', 'Shooting brake')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('Przedni', 'Przedni'), ('4x4', '4x4'), ('Tylni', 'Tylni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Elektryczny', 'Elektryczny'), ('Benzyna', 'Benzyna'), ('Hybryda', 'Hybryda'), ('Diesel', 'Diesel')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('7', '7'), ('5', '5'), ('8', '8'), ('6', '6')], max_length=8),
        ),
    ]
